version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
  build:
    commands:
      - echo "SKIP_BUILD is set to $SKIP_BUILD"
      - echo "$Branch"
artifacts:
  files:
    - '**/*'
