version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    
  pre_build: 
    commands:
      - echo "Installing"

  build:
    commands:
      - echo "Build phase executed."  
  
  post_build:
    commands:
      - echo "Deploy to $STAGE Environment"

artifacts:
  files:
    - '**/*'
