version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
  build:
    commands:    
      - |
        if [ "$SKIP_NEXT_STAGE" == "true" ]; then
          echo "Skipping the next stage..."
          exit 0
        fi
      - echo "Running the build script..."
      - echo "Making run.sh executable..."
      - chmod +x run.sh
      - echo "Running run.sh..."      
      - ./run.sh    
artifacts:
  files:
    - '**/*'
  
