version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
  build:
    commands:
      - echo "SKIP_BUILD is set to $SKIP_BUILD"
      - if [[ "$SKIP_BUILD" -eq "true" ]]; then
          echo "Skipping build phase as SKIP_BUILD is set to true.";
        else
          echo "Running build phase...";
          chmod +x run.sh;
          ./run.sh;
        fi 
artifacts:
  files:
    - '**/*'
