build:
  commands:
    - echo "SKIP_BUILD is set to $SKIP_BUILD"
    - if [ "$SKIP_BUILD" = "true" ]; then
        echo "Skipping build phase as SKIP_BUILD is set to true.";
      else
        echo "Running build phase...";
        chmod +x run.sh;
        ./run.sh;
      fi
