version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing"

  build:
    commands:
      - if [ "$SKIP_BUILD" = "true" ]; then
          echo "Skipping build phase as SKIP_BUILD is set to true.";
        else
          echo "Running build phase...";
          chmod +x run.sh;
          ./run.sh;
        fi

  post_build:
    commands:
      - echo "Post-build phase executed."

artifacts:
  files:
    - '**/*'
