version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
  build:
    commands:
      - echo "SKIP_BUILD is set to $SKIP_BUILD"
      - echo "$new"
      - echo "CODEBUILD_SRC_DIR -> $CODEBUILD_SRC_DIR"
      - echo "CODEBUILD_WEBHOOK_BASE_REF -> $CODEBUILD_WEBHOOK_BASE_REF"
      - echo "CODEBUILD_WEBHOOK_EVENT -> $CODEBUILD_WEBHOOK_EVENT"
      - echo "CODEBUILD_WEBHOOK_MERGE_COMMIT -> $CODEBUILD_WEBHOOK_MERGE_COMMIT"
      - echo "CODEBUILD_WEBHOOK_PREV_COMMIT -> $CODEBUILD_WEBHOOK_PREV_COMMIT"
      - echo "CODEBUILD_WEBHOOK_HEAD_REF -> $CODEBUILD_WEBHOOK_HEAD_REF"
      - echo "CODEBUILD_WEBHOOK_TRIGGER -> $CODEBUILD_WEBHOOK_TRIGGER"
artifacts:
  files:
    - '**/*'
